// Quiz question bank (loaded before main script)
// TERMINAL TRIVIA LOGIC - ONE QUESTION AT A TIME
const ALL_QUESTIONS = {
  devops: [
    { question: "What does CI/CD stand for in DevOps?", answers: ["Continuous Integration / Continuous Deployment", "Code Integration / Code Deployment", "Cloud Infrastructure / Cloud Delivery", "Continuous Inspection / Continuous Delivery"], correct: "Continuous Integration / Continuous Deployment" },
    { question: "Which AWS service stores Docker container images?", answers: ["AWS S3", "AWS ECR", "AWS ECS", "AWS CloudFront"], correct: "AWS ECR" },
    { question: "What is the purpose of a Dockerfile?", answers: ["To run containers", "To define how a Docker image is built", "To store container logs", "To configure Docker networking"], correct: "To define how a Docker image is built" },
    { question: "Which Terraform command creates the execution plan?", answers: ["terraform apply", "terraform init", "terraform plan", "terraform validate"], correct: "terraform plan" },
    { question: "In Kubernetes, what is a Pod?", answers: ["A VM in the cluster", "The smallest deployable unit containing one or more containers", "A load balancer", "A storage volume"], correct: "The smallest deployable unit containing one or more containers" },
    { question: "What does AWS IAM stand for?", answers: ["Internet Access Management", "Identity and Access Management", "Infrastructure Automation Manager", "Internal AWS Module"], correct: "Identity and Access Management" },
    { question: "Which tool is used for configuration management in DevOps?", answers: ["Terraform", "Ansible", "Prometheus", "Grafana"], correct: "Ansible" },
    { question: "What command lists all running Docker containers?", answers: ["docker ps", "docker ls", "docker list", "docker status"], correct: "docker ps" },
    { question: "In Jenkins, what is a Jenkinsfile?", answers: ["A Jenkins log file", "A pipeline definition file as code", "Jenkins configuration backup", "Jenkins plugin file"], correct: "A pipeline definition file as code" },
    { question: "What AWS service provides auto-scaling for applications?", answers: ["AWS CloudWatch", "AWS Auto Scaling", "AWS Elastic Beanstalk", "AWS Load Balancer"], correct: "AWS Auto Scaling" },
    { question: "What does 'Infrastructure as Code' (IaC) mean?", answers: ["Writing code inside cloud consoles", "Managing infrastructure using code/config files", "Coding within virtual machines", "Writing scripts to test infrastructure"], correct: "Managing infrastructure using code/config files" },
    { question: "Which monitoring tool is commonly paired with Prometheus for dashboards?", answers: ["Kibana", "Grafana", "DataDog", "Splunk"], correct: "Grafana" },
    { question: "What does `kubectl get pods` do?", answers: ["Deletes all pods", "Lists all pods in the current namespace", "Creates new pods", "Restarts failed pods"], correct: "Lists all pods in the current namespace" },
    { question: "What is the purpose of AWS S3?", answers: ["Running virtual machines", "Scalable object storage", "Managing DNS records", "Running containers"], correct: "Scalable object storage" },
    { question: "What is a Docker volume used for?", answers: ["Increasing CPU for containers", "Persistent data storage outside the container", "Networking between containers", "Building Docker images faster"], correct: "Persistent data storage outside the container" },
    { question: "Which Kubernetes object manages stateless application deployments?", answers: ["StatefulSet", "DaemonSet", "Deployment", "Job"], correct: "Deployment" },
    { question: "What is the purpose of `terraform init`?", answers: ["Creates infrastructure", "Initializes working directory and downloads providers", "Destroys infrastructure", "Validates configuration"], correct: "Initializes working directory and downloads providers" },
    { question: "What does a GitHub Actions workflow file use as its format?", answers: ["JSON", "XML", "YAML", "TOML"], correct: "YAML" },
    { question: "Which command builds a Docker image from a Dockerfile?", answers: ["docker run", "docker create", "docker build", "docker start"], correct: "docker build" },
    { question: "What is Blue-Green deployment?", answers: ["Deploying to dev and prod simultaneously", "Running two identical environments and switching traffic", "Blue = backend, Green = frontend", "A Docker networking mode"], correct: "Running two identical environments and switching traffic" },
    { question: "What does AWS VPC stand for?", answers: ["Virtual Private Cloud", "Virtual Public Cloud", "Virtual Protocol Controller", "Variable Port Configuration"], correct: "Virtual Private Cloud" },
    { question: "In DevOps, what is 'shift left' testing?", answers: ["Moving QA to the end of pipeline", "Testing earlier in the development cycle", "Shifting deployments to the left region", "A Git branching strategy"], correct: "Testing earlier in the development cycle" },
    { question: "What is a Kubernetes Namespace used for?", answers: ["Storing secrets", "Isolating resources within a cluster", "Load balancing", "Persistent storage"], correct: "Isolating resources within a cluster" },
    { question: "Which AWS service is used for serverless computing?", answers: ["AWS EC2", "AWS ECS", "AWS Lambda", "AWS Fargate"], correct: "AWS Lambda" },
    { question: "What is the Azure equivalent of AWS IAM?", answers: ["Azure AD (Entra ID)", "Azure Key Vault", "Azure Policy", "Azure RBAC only"], correct: "Azure AD (Entra ID)" },
    { question: "What does `docker-compose up -d` do?", answers: ["Builds images only", "Starts all services in detached mode", "Stops all containers", "Deletes volumes"], correct: "Starts all services in detached mode" },
    { question: "Which AWS service is used for managed Kubernetes?", answers: ["AWS ECS", "AWS EKS", "AWS Fargate", "AWS Batch"], correct: "AWS EKS" },
    { question: "What is the Azure equivalent of AWS S3?", answers: ["Azure Files", "Azure Blob Storage", "Azure Disk", "Azure Data Lake"], correct: "Azure Blob Storage" },
    { question: "What is a Helm chart in Kubernetes?", answers: ["A monitoring dashboard", "A package manager for Kubernetes applications", "A load balancer config", "A secrets manager"], correct: "A package manager for Kubernetes applications" },
    { question: "What does `terraform destroy` do?", answers: ["Plans infrastructure removal", "Removes all infrastructure managed by Terraform", "Validates and destroys syntax errors", "Deletes the state file only"], correct: "Removes all infrastructure managed by Terraform" }
  ],
  linux: [
    { question: "Which command displays the current working directory?", answers: ["ls", "cd", "pwd", "grep"], correct: "pwd" },
    { question: "How do you change file permissions in Linux?", answers: ["chown", "chgrp", "chmod", "ln"], correct: "chmod" },
    { question: "Which command installs packages on Debian/Ubuntu?", answers: ["yum", "rpm", "apt install", "pacman"], correct: "apt install" },
    { question: "What command stops a running process by its PID?", answers: ["stop", "kill", "halt", "terminate"], correct: "kill" },
    { question: "Which file contains a list of user accounts?", answers: ["/etc/shadow", "/etc/fstab", "/etc/passwd", "/var/log/syslog"], correct: "/etc/passwd" },
    { question: "Which command views the end of a file in real-time?", answers: ["cat", "less", "tail -f", "head"], correct: "tail -f" },
    { question: "What does `set -euo pipefail` do in bash?", answers: ["Enables verbose mode", "Exits on error, unset vars, and pipe failures", "Sets environment variables", "Enables debugging"], correct: "Exits on error, unset vars, and pipe failures" },
    { question: "Which command shows disk usage of a directory?", answers: ["df -h", "ls -la", "du -sh", "fdisk -l"], correct: "du -sh" },
    { question: "What does cron expression `0 2 * * *` mean?", answers: ["Every 2 minutes", "Every 2 hours", "At 2:00 AM every day", "Every 2nd day"], correct: "At 2:00 AM every day" },
    { question: "Which command searches for text inside files?", answers: ["find", "locate", "grep", "sed"], correct: "grep" },
    { question: "What command displays running processes in real-time?", answers: ["ps aux", "jobs", "top", "ls -la"], correct: "top" },
    { question: "What does `chmod 755 script.sh` do?", answers: ["Makes file read-only", "Owner can rwx, group and others can r-x", "Removes all permissions", "Gives everyone full access"], correct: "Owner can rwx, group and others can r-x" },
    { question: "Which command finds files modified in the last 7 days?", answers: ["locate -d 7", "grep -r 7days", "find / -mtime -7", "ls --modified 7"], correct: "find / -mtime -7" },
    { question: "What does `>&2` mean in a bash script?", answers: ["Redirect to file descriptor 2 (stderr)", "Redirect from file 2", "Run command with PID 2", "Double output redirect"], correct: "Redirect to file descriptor 2 (stderr)" },
    { question: "Which command shows all open network ports?", answers: ["ifconfig", "netstat -tulnp", "ping", "route"], correct: "netstat -tulnp" },
    { question: "What is the shebang line for bash scripts?", answers: ["#!/bin/sh", "#!/bin/bash", "#!bash", "#!/usr/bin/env sh"], correct: "#!/bin/bash" },
    { question: "Which command elevates user privileges temporarily?", answers: ["su", "sudo", "root", "login"], correct: "sudo" },
    { question: "What does `df -h` display?", answers: ["Directory files", "Disk filesystem usage in human-readable format", "Default file headers", "Diff of files"], correct: "Disk filesystem usage in human-readable format" },
    { question: "How do you make a bash script executable?", answers: ["bash run script.sh", "chmod +x script.sh", "exec script.sh", "make executable script.sh"], correct: "chmod +x script.sh" },
    { question: "What does `awk '{print $2}' file.txt` do?", answers: ["Prints the first column", "Prints the second column of each line", "Deletes second line", "Counts lines"], correct: "Prints the second column of each line" }
  ]
};

// Azure questions appended separately for clarity
ALL_QUESTIONS.azure = [
  { question: "What is the Azure equivalent of AWS EC2?", answers: ["Azure Functions", "Azure Virtual Machines", "Azure App Service", "Azure Container Instances"], correct: "Azure Virtual Machines" },
  { question: "What is Azure Resource Manager (ARM)?", answers: ["A deployment and management service for Azure resources", "A virtual machine manager", "Azure's DNS service", "A monitoring tool"], correct: "A deployment and management service for Azure resources" },
  { question: "What does Azure DevOps Pipelines do?", answers: ["Manages virtual networks", "Automates build, test, and deploy workflows", "Stores container images", "Monitors cloud costs"], correct: "Automates build, test, and deploy workflows" },
  { question: "What is the Azure equivalent of AWS Lambda?", answers: ["Azure Logic Apps", "Azure Functions", "Azure Runbooks", "Azure Container Apps"], correct: "Azure Functions" },
  { question: "What is Azure Blob Storage used for?", answers: ["Running virtual machines", "Unstructured object storage like images and backups", "Relational database storage", "Running serverless code"], correct: "Unstructured object storage like images and backups" },
  { question: "What is Azure Kubernetes Service (AKS)?", answers: ["A managed Kubernetes cluster service on Azure", "Azure's container registry", "An Azure VM scaling tool", "Azure's CI/CD tool"], correct: "A managed Kubernetes cluster service on Azure" },
  { question: "What does Azure Key Vault do?", answers: ["Manages virtual networks", "Stores and manages secrets, keys, and certificates", "Hosts web applications", "Provisions Azure VMs"], correct: "Stores and manages secrets, keys, and certificates" },
  { question: "What is an Azure Resource Group?", answers: ["A billing account", "A logical container that holds related Azure resources", "A virtual network", "A storage container"], correct: "A logical container that holds related Azure resources" },
  { question: "What is Azure Monitor used for?", answers: ["Managing user access", "Collecting metrics, logs, and alerts for Azure resources", "Deploying infrastructure", "Managing subscriptions"], correct: "Collecting metrics, logs, and alerts for Azure resources" },
  { question: "What is Azure Active Directory (Entra ID)?", answers: ["A file directory service only", "Microsoft's cloud-based identity and access management service", "An on-prem AD extension only", "Azure's DNS service"], correct: "Microsoft's cloud-based identity and access management service" },
  { question: "What does RBAC stand for in Azure?", answers: ["Resource Based Access Control", "Role Based Access Control", "Remote Backup and Cloud", "Routing Bridge and Control"], correct: "Role Based Access Control" },
  { question: "What is an Azure Subscription?", answers: ["A billing and access container for Azure resources", "A VM type in Azure", "An Azure storage tier", "An Azure deployment region"], correct: "A billing and access container for Azure resources" },
  { question: "Which Azure service is equivalent to AWS CloudFormation?", answers: ["Azure DevOps", "Azure ARM Templates / Bicep", "Azure Policy", "Azure Blueprints"], correct: "Azure ARM Templates / Bicep" },
  { question: "What is Azure Container Registry (ACR)?", answers: ["A managed Kubernetes service", "A private Docker image registry on Azure", "Azure's serverless compute", "An Azure load balancer"], correct: "A private Docker image registry on Azure" },
  { question: "What is Azure Log Analytics?", answers: ["A tool for writing Azure scripts", "A workspace for querying and analyzing Azure logs", "An Azure billing tool", "A code repository on Azure"], correct: "A workspace for querying and analyzing Azure logs" },
  { question: "What is the Azure CLI command to login?", answers: ["azure login", "az login", "az connect", "azure auth"], correct: "az login" },
  { question: "What is Azure Availability Zone?", answers: ["A geographic region", "A physically separate datacenter within a region for redundancy", "A virtual network zone", "A pricing tier"], correct: "A physically separate datacenter within a region for redundancy" },
  { question: "What is Azure Bastion used for?", answers: ["Storing encryption keys", "Secure RDP/SSH access to VMs without public IPs", "Container orchestration", "DNS management"], correct: "Secure RDP/SSH access to VMs without public IPs" },
  { question: "What does Azure Policy do?", answers: ["Manages user passwords", "Enforces organizational standards and compliance on Azure resources", "Manages billing only", "Monitors application performance"], correct: "Enforces organizational standards and compliance on Azure resources" },
  { question: "What is the difference between Azure Scale Sets and Azure Load Balancer?", answers: ["They are the same thing", "Scale Sets auto-scale VMs; Load Balancer distributes traffic", "Load Balancer scales VMs; Scale Sets balance traffic", "Scale Sets are for storage, Load Balancer for compute"], correct: "Scale Sets auto-scale VMs; Load Balancer distributes traffic" }
];
